/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.addControl;
import javax.swing.JOptionPane;

/**
 *
 * @author This PC
 */
public class AddOrder extends javax.swing.JFrame {

    /**
     * Creates new form AddOrder
     */
    public AddOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ordDateBTN = new javax.swing.JTextField();
        delvryDateBTN = new javax.swing.JTextField();
        pymntBOX = new javax.swing.JComboBox<>();
        orlBTN = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        ordidBTN = new javax.swing.JTextField();
        cstmidBTN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CustomerID:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Order Date:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Payment Method:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Delivery Date:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("orderList");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, -1));

        ordDateBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(ordDateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 270, -1));

        delvryDateBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.add(delvryDateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 270, -1));

        pymntBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Bank transfer", "Cash on delivery" }));
        pymntBOX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        pymntBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pymntBOXActionPerformed(evt);
            }
        });
        jPanel1.add(pymntBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 100, -1));

        orlBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        orlBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orlBTNActionPerformed(evt);
            }
        });
        jPanel1.add(orlBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 270, 70));

        addBTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBTN.setText("ADD");
        addBTN.setBorder(new javax.swing.border.MatteBorder(null));
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 100, 30));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        kGradientPanel1.setkEndColor(new java.awt.Color(51, 51, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 51));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 153));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 204, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD Order");
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 200, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 100, 30));

        ordidBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        kGradientPanel2.add(ordidBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 270, -1));

        cstmidBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        kGradientPanel2.add(cstmidBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 270, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("OrderID :");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kGradientPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 90, 30));

        kGradientPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 520));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pymntBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pymntBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pymntBOXActionPerformed

    private void orlBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orlBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orlBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
       /* 
        String ordId = ordidBTN.getText();
        String customerid = cstmidBTN.getText();
        String ordDate = ordDateBTN.getText();
        String delvrDate = delvryDateBTN.getText();
        String paymnMehd = (String) pymntBOX.getSelectedItem();
        String descrptn = descripBTN.getText();
        
        try{
            int id = Integer.parseInt(ordId);
            int cuId = Integer.parseInt(customerid);
            addControl obj = new addControl();
            obj.item(id, cuId, ordDate, delvrDate, paymnMehd, descrptn);
        }catch (NumberFormatException e){
            
        }
        
        */
        
        
   /*     
    String ordId = ordidBTN.getText();
    String customerid = cstmidBTN.getText();
    String ordDate = ordDateBTN.getText();
    String delvrDate = delvryDateBTN.getText();
    String paymnMehd = (String) pymntBOX.getSelectedItem();
    String descrptn = descripBTN.getText();
    
    if (ordId.isEmpty() || customerid.isEmpty() || ordDate.isEmpty() || delvrDate.isEmpty() || paymnMehd.isEmpty() || descrptn.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all fields");
        return;
    }
    
    try {
        int id = Integer.parseInt(ordId);
        int cuId = Integer.parseInt(customerid);
        addControl obj = new addControl();
        obj.item(id, cuId, ordDate, delvrDate, paymnMehd, descrptn);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid number format");
    }*/

    String ordId = ordidBTN.getText();
    String customerid = cstmidBTN.getText();
    String ordDate = ordDateBTN.getText();
    String delvrDate = delvryDateBTN.getText();
    String paymnMehd = (String) pymntBOX.getSelectedItem();
    String orderItem = orlBTN.getText();

    if (ordId.isEmpty() || customerid.isEmpty() || ordDate.isEmpty() || delvrDate.isEmpty() || paymnMehd.isEmpty() || orderItem.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all fields");
        return;
    }

    try {
        int id = Integer.parseInt(ordId);
        int cuId = Integer.parseInt(customerid);
        addControl obj = new addControl();
        obj.item(id, cuId, ordDate, delvrDate, paymnMehd, orderItem);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid number format");
    }

        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Order B = new Order();
        B.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JTextField cstmidBTN;
    private javax.swing.JTextField delvryDateBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTextField ordDateBTN;
    private javax.swing.JTextField ordidBTN;
    private javax.swing.JTextField orlBTN;
    private javax.swing.JComboBox<String> pymntBOX;
    // End of variables declaration//GEN-END:variables
}
